### ISSUE TITLE
eBloc on Windows

### ISSUE THREAD

**Issue by mehmetsefa2644** [avatar-lavventura/eblocPOA#19]
Windows uzerinde calistirilabilecek sekilde eBloc u modify ettim, permissionlardan beni eklerseniz, windows branchina pushlayabilirim, boylelikle diger windows kullanicilari da ebloc u kullanabilir.

**Comment by mehmetsefa2644** [comment]
@avatar-lavventura @ebloc

**Comment by mehmetsefa2644** [comment]
windows versiyonunu: https://github.com/mehmetsefa2644/eblocPOA

**Comment by avatar-lavventura** [comment]
Thank you @mehmetsefa2644

**Comment by ebloc** [comment]
Thank you @mehmetsefa2644
